apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: unleash
spec:
  itemPath: "vaults/aks-beta-vault/items/unleash" 
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    io.kompose.service: unleash-server
  name: unleash-server
spec:
  ports:
    - name: "4242"
      port: 4242
  type: LoadBalancer
  selector:
    io.kompose.service: unleash-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: unleash-server
  name: unleash-server
spec:
  replicas: 1
  minReadySeconds: 30
  revisionHistoryLimit: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      io.kompose.service: unleash-server
  template:
    metadata:
      labels:
        io.kompose.service: unleash-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4242"
        prometheus.io/path: "/internal-backstage/prometheus"
    spec:
      containers:
        - name: unleash-server
          image: fintlabsacr.azurecr.io/fint-unleash:dummy
          ports:
            - containerPort: 4242
 #         readinessProbe:
 #           initialDelaySeconds: 30
 #           timeoutSeconds: 5
 #           httpGet:
 #             port: 4242
 #             path: /client/features
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              cpu: "100m"
              memory: "32Mi"
          env:
            - name: TZ
              value: Europe/Oslo
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: unleash
            - name: DATABASE_SSL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_SSL
                  name: unleash
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_CLIENT_ID
                  name: unleash
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_CLIENT_SECRET
                  name: unleash
            - name: GOOGLE_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_CALLBACK_URL
                  name: unleash