apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - patch: |-
      - op: replace
        path: "/spec/onePassword/itemPath"
        value: "vaults/aks-api-vault/items/unleash"
    target:
      kind: Application
      name: fint-unleash
  - patch: |-
      - op: replace
        path: "/spec/url/hostname"
        value: "unleash-api.fintlabs.no"
    target:
      kind: Application
      name: fint-unleash